OnlineShop/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

OnlineShop/Controllers/HomeController.cs
using Model.Dao;
using OnlineShop.Common;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Slides = new SlideDao().ListAll();
            var productDao = new ProductDao();
            ViewBag.NewProducts = productDao.ListNewProduct(4);
            ViewBag.ListFeatureProducts = productDao.ListFeatureProduct(4);
            ViewBag.session = (UserLogin)Session[CommonConstants.MEMBER_SESSION];
            return View();
        }

        [ChildActionOnly]
        [OutputCache(Duration = 3600 * 24)]
        public ActionResult MainMenu()
        {
            var model = new MenuDao().ListByGroupId(1);
            return PartialView(model);
        }
        [ChildActionOnly]
        [OutputCache(Duration = 3600 * 24)]
        public ActionResult TopMenu()
        {
            var model = new MenuDao().ListByGroupId(2);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult HeaderCart()
        {
            var cart = Session[CommonConstants.CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }

            return PartialView(list);
        }
        [ChildActionOnly]
        [OutputCache(Duration = 3600 * 24)]
        public ActionResult Footer()
        {
            var model = new FooterDao().GetFooter();
            return PartialView(model);
        }
    }
}

OnlineShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Dao;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult ProductCategory()
        {
            var model = new ProductCategoryDao().ListAll();
            return PartialView(model);
        }
        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            },JsonRequestBehavior.AllowGet);
        }

        public ActionResult Category(long cateId, int page = 1, int pageSize = 1)
        {
            var category = new CategoryDao().ViewDetail(cateId);
            ViewBag.Category = category;
            int totalRecord = 0;
            var model = new ProductDao().ListByCategoryId(cateId, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        public ActionResult Search(string keyword, int page = 1, int pageSize = 1)
        {
            int totalRecord = 0;
            var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        [OutputCache(CacheProfile = "Cache1DayForProduct")]
        public ActionResult Detail(long id)
        {
            var product = new ProductDao().ViewDetail(id);
            ViewBag.Category = new ProductCategoryDao().ViewDetail(product.CategoryID.Value);
            ViewBag.RelatedProducts = new ProductDao().ListRelatedProducts(id);
            return View(product);
        }
    }
}

OnlineShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var slides = (List<Model.EF.Slide>)ViewBag.Slides;
    var listNewProducts = (List<Model.EF.Product>)ViewBag.NewProducts;
    var listFeatureProducts = (List<Model.EF.Product>)ViewBag.ListFeatureProducts;
}
@section slide
{
    <div class="header_slide">
        <div class="header_bottom_left">
            <div class="categories">
                @{ Html.RenderAction("ProductCategory", "Product");}
            </div>
        </div>
        <div class="header_bottom_right">
            <div class="slider">
                <div id="slider">
                    <div id="mover">
                        @foreach (var item in slides)
                        {
                            <div id="slide-1" class="slide">
                                <div class="slider-img">
                                    <a href="@item.Link"><img src="@item.Image" alt="learn more" /></a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        }
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
}
<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>Sản phẩm mới</h3>
        </div>
        <div class="see">
            <p><a href="/san-pham">Xem toàn bộ sản phẩm</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in listNewProducts)
        {
            var url = "/chi-tiet/" + item.MetaTitle + "-" + item.ID;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@url"><img src="@item.Image" alt="@item.Name" /></a>
                <h2>@item.Name</h2>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@(item.Price.HasValue ? item.Price.Value.ToString("N0") : "Liên hệ")</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/them-gio-hang?productId=@item.ID&quantity=1">Thêm vào giỏ</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        }

    </div>
    <div class="content_bottom">
        <div class="heading">
            <h3>Sản phẩm hot</h3>
        </div>
        <div class="see">
            <p><a href="/san-pham">Xem tất cả</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in listFeatureProducts)
        {
            var url = "/chi-tiet/" + item.MetaTitle + "-" + item.ID;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@url"><img src="@item.Image" alt="@item.Name" /></a>
                <h2>@item.Name</h2>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@(item.Price.HasValue ? item.Price.Value.ToString("N0") : "Liên hệ")</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/them-gio-hang?productId=@item.ID&quantity=1">Thêm vào giỏ</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        }
    </div>
</div>