OnlineShop/Controllers/UserController.cs
using BotDetect.Web.UI.Mvc;
using Facebook;
using Model.Dao;
using Model.EF;
using OnlineShop.Common;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace OnlineShop.Controllers
{
    
    public class UserController : Controller
    {
        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }

        // GET: User
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // Login Controller
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    userSession.GroupID = user.GroupID;
                    Session.Add(CommonConstants.MEMBER_SESSION, userSession);
                    return Redirect("/");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else
                {
                    ModelState.AddModelError("", "đăng nhập không đúng.");
                }
            }
            return View(model);
        }

        // Login facebook
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;

                var user = new User();
                user.Email = email;
                user.UserName = email;
                user.Status = true;
                user.Name = firstname + " " + middlename + " " + lastname;
                user.CreatedDate = DateTime.Now;
                var resultInsert = new UserDao().InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    userSession.GroupID = user.GroupID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                }
            }
            return Redirect("/");
        }

        // Logout
        public ActionResult Logout()
        {
            Session.Clear();
            return Redirect("/");
        }
        
        [HttpPost]
        [CaptchaValidation("CaptchaCode", "registerCapcha", "Mã xác nhận không đúng!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new User();
                    user.Name = model.Name;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.UserName = model.UserName;
                    user.GroupID = "MEMBER";
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    user.Address = model.Address;
                    user.CreatedDate = DateTime.Now;
                    user.Status = true;
                    if (!string.IsNullOrEmpty(model.ProvinceID))
                    {
                        user.ProvinceID = int.Parse(model.ProvinceID);
                    }
                    if (!string.IsNullOrEmpty(model.DistrictID))
                    {
                        user.DistrictID = int.Parse(model.DistrictID);
                    }
                   
                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            return View(model);
        }

        public JsonResult LoadProvince()
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~/assets/client/data/Provinces_Data.xml"));

            var xElements = xmlDoc.Element("Root").Elements("Item").Where(x => x.Attribute("type").Value == "province");
            var list = new List<ProvinceModel>();
            ProvinceModel province = null;
            foreach (var item in xElements)
            {
                province = new ProvinceModel();
                province.ID = int.Parse(item.Attribute("id").Value);
                province.Name = item.Attribute("value").Value;
                list.Add(province);

            }
            return Json(new
            {
                data = list,
                status = true
            });
        }
        public JsonResult LoadDistrict(int provinceID)
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~/assets/client/data/Provinces_Data.xml"));

            var xElement = xmlDoc.Element("Root").Elements("Item")
                .Single(x => x.Attribute("type").Value == "province" && int.Parse(x.Attribute("id").Value) == provinceID);

            var list = new List<DistrictModel>();
            DistrictModel district = null;
            foreach (var item in xElement.Elements("Item").Where(x => x.Attribute("type").Value == "district"))
            {
                district = new DistrictModel();
                district.ID = int.Parse(item.Attribute("id").Value);
                district.Name = item.Attribute("value").Value;
                district.ProvinceID = int.Parse(xElement.Attribute("id").Value);
                list.Add(district);

            }
            return Json(new
            {
                data = list,
                status = true
            });
        }

    }
}

OnlineShop/Views/Shared/401.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        Bạn không có quyền truy cập trang này.
    </div>
</body>
</html>

OnlineShop/Views/Shared/HeaderCart.cshtml
@model List<OnlineShop.Models.CartItem>
<div class="cart">
    <p>
        Chào mừng bạn đến với website <span><a href="/gio-hang" style="color: red">Giỏ hàng:</a></span><div id="dd" class="wrapper-dropdown-2">
            @Model.Count sản phẩm
        </div>
    </p>
</div>

OnlineShop/Views/Shared/MainMenu.cshtml
@model List<Model.EF.Menu>
<div class="menu">
    <ul>
        @foreach (var item in Model)
        {
            <li>
                <a href="@item.Link" target="@item.Target">@item.Text</a>     
            </li>
        }
        <div class="clear"></div>
    </ul>
</div>

OnlineShop/Views/Shared/ProductCategory.cshtml
@model List<Model.EF.ProductCategory>
<ul>
    <h3>Danh mục sản phẩm</h3>
    @foreach (var item in Model.Where(x => x.ParentID == null))
    {
        var child = Model.Where(x => x.ParentID == item.ID);
        var parentClass = child.Count() > 0 ? "class=dropdown-toggle data-toggle=dropdown" : "";
        <li class="dropdown">
            <a href="/san-pham/@item.MetaTitle-@item.ID" @parentClass>@item.Name</a>
            @if (child.Count() > 0)
            {
                <ul class="dropdown-menu">
                    @foreach (var childItem in child)
                    {
                        <li><a href="/san-pham/@childItem.MetaTitle-@childItem.ID">@childItem.Name</a></li>
                    }

                </ul>
            }

        </li>
    }
</ul>

OnlineShop/Views/Shared/TopMenu.cshtml
@*@model List<Model.EF.Menu>
<div class="call">
    <p><span>Cần trợ giúp?</span> hãy gọi <span class="number">038-233-9971</span></p>
</div>
<div class="account_desc">
    @{
        var session2 = (UserLogin)Session[OnlineShop.Common.CommonConstants.MEMBER_SESSION];

    if (session2 == null)
    {
        <ul>
            @foreach (var item in Model)
            {
                <li><a href="@item.Link" target="@item.Target">@item.Text</a></li>
            }
        </ul>
    }
    else
    {
        <ul>
            <li>Xin chào:@session2.UserName</li>
            <li>@Html.ActionLink("Thoát", "Logout", "User")</li>
        </ul>
    }
        }
</div>
<div class="clear"></div>*@

OnlineShop/Views/Shared/_Layout.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Online Shop</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="/assets/client/css/bootstrap.css" rel="stylesheet" />
    <link href="/assets/client/css/boostrap-social.css" rel="stylesheet" />
    <link href="/assets/client/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/assets/client/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="/assets/client/css/jquery-ui.css" rel="stylesheet" />
    <link href="/assets/client/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/client/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Latest compiled and minified JavaScript -->
    <script src="/assets/client/js/jquery-1.11.3.min.js"></script>
    <script src="/assets/client/js/jquery-ui.js"></script>
    <script src="/assets/client/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/assets/client/js/move-top.js"></script>
    <script type="text/javascript" src="/assets/client/js/easing.js"></script>
    <script type="text/javascript" src="/assets/client/js/startstop-slider.js"></script>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p><span>Cần trợ giúp?</span> hãy gọi <span class="number">038-233-9971</span></p>
                </div>
                <div class="account_desc">
                    @{
                        var session = (UserLogin)Session[OnlineShop.Common.CommonConstants.MEMBER_SESSION];

                        if (session == null)
                        {
                           <ul>
                               <li><a href="/dang-nhap">Đăng nhập</a></li>
                               <li><a href="/dang-ky">Đăng ký</a></li>
                           </ul>
                        }
                        else
                        {
                            <ul>
                                <li>Xin chào: @session.UserName</li>
                                <li>
                                    @Html.ActionLink("Thoát","Logout","User")
                                </li>
                            </ul>
                        }
                    }
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    <a href="/" ref="nofollow"><img src="/assets/client/images/logo.png" alt="" /></a>
                </div>
                @{ Html.RenderAction("HeaderCart", "Home");}
                <script type="text/javascript">
			function DropDown(el) {
				this.dd = el;
				this.initEvents();
			}
			DropDown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						event.stopPropagation();
					});
				}
			}

			$(function() {

				var dd = new DropDown( $('#dd') );

				$(document).click(function() {
					// all dropdowns
					$('.wrapper-dropdown-2').removeClass('active');
				});

			});

                </script>
                <div class="clear"></div>
            </div>
            <div class="header_bottom">
                @{Html.RenderAction("MainMenu", "Home"); }
                <div class="search_box">
                    <form action="/tim-kiem" method="get">
                        <input type="text" id="txtKeyword" name="keyword" placeholder="Gõ từ khoá"><input type="submit" value="">
                    </form>
                </div>
                <div class="clear"></div>
            </div>
            @RenderSection("slide", required: false)
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Thông tin chung</h4>
                    <ul>
                        <li><a href="about.html">Về chúng tôi</a></li>
                        <li><a href="contact.html">Dịch vụ khách hàng</a></li>
                        <li><a href="delivery.html">Đặt hàng</a></li>
                        <li><a href="contact.html">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Lựa chọn chúng tôi</h4>
                    <ul>
                        <li><a href="#">Chính sách bảo mật</a></li>
                        <li><a href="contact.html">Bản đồ</a></li>
                        <li><a href="#">Từ khóa tìm kiếm</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Tài khoản</h4>
                    <ul>
                        <li><a href="contact.html">Đăng ký</a></li>
                        <li><a href="index.html">Xem giỏ hàng</a></li>
                        <li><a href="#">Kiểm tra đơn hàng</a></li>
                        <li><a href="contact.html">Trợ giúp</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Thông tin liên hệ</h4>
                    <ul>
                        <li><span>038-233-9971</span></li>
                        <li><span>032-123-0000</span></li>
                    </ul>
                    <div class="social-icons">
                        <h4>Theo dõi chúng tôi</h4>
                        <ul>
                            <li><a href="#" target="_blank"><img src="/Assets/Client/images/facebook.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="/Assets/Client/images/twitter.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="/Assets/Client/images/skype.png" alt="" /> </a></li>
                            <li><a href="#" target="_blank"> <img src="/Assets/Client/images/dribbble.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"> <img src="/Assets/Client/images/linkedin.png" alt="" /></a></li>
                            <div class="clear"></div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy_right" style="display: none;">
            <p>&copy; 2013 home_shoppe. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <a href="#" id="toTop"><span id="toTopHover"> </span></a>
    <script src="/assets/client/js/controller/baseController.js"></script>
    @RenderSection("jsFooter", required: false)
</body>
</html>